seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/search.rb
    page_type: search
    disabled: false

  - file: ./parsers/products.rb
    page_type: products
    disabled: false

exporters:
  - file: ./exporters/products_json.yaml